FROM apache/airflow:2.10.2-python3.12

USER root
RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements.txt .
RUN pip install --no-cache-dir apache-airflow[postgres,kafka] && \
    pip install --no-cache-dir -r requirements.txt

WORKDIR /opt/airflow
COPY . .